language: python
python:
  - "3.5"
  - "3.5-dev"
  - "3.6"
  - "3.6-dev"
  # - "3.7"   # 3.7 not currently available on travis?!
  - "3.7-dev"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install numpy --upgrade
  - pip install .

# command to run tests
script:
  - python -c "import numpy; print(numpy.__version__); import scipy; print(scipy.__version__)"
  - nosetests --with-coverage --cover-inclusive --cover-package=kdes
  - jupyter nbconvert --ExecutePreprocessor.kernel_name=python --ExecutePreprocessor.timeout=600 --to notebook --execute notebooks/kde.ipynb
  - python -c "import kdes; print(kdes.__file__)"

after_success:
  - codecov
